---
name: Update TvGuide

on:
  schedule:
    - cron: '0 21 * * *'

  push:
    branches: [master]
    paths:
      - 'channels.json'
      - 'tvguide.json'
      - 'tvguide.rb'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Generate EPG
        run: bundle exec rake epg:generate

      - name: Upload assets
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: tvguide.xml*
          tag: IPTV
          body: Latest generated release
          overwrite: true
